#!/usr/bin/env python3


import argparse
import sys
import cherrypy
import threading
import subprocess


def http_methods_allowed(methods=['GET', 'HEAD']):
    method = cherrypy.request.method.upper()
    if method not in methods:
        cherrypy.response.headers['Allow'] = ", ".join(methods)
        raise cherrypy.HTTPError(405)

cherrypy.tools.allow = cherrypy.Tool('on_start_resource', http_methods_allowed)


class RootPage:

    @cherrypy.expose
    @cherrypy.tools.allow(methods=['GET', 'HEAD'])
    def stream(self, input=None, board=None, verbose=None, codec=None,
               device=None, noAudio=None, lookAhead=None, quality=None,
               gopSize=None, preset=None):
        def coalesce(opt, arg1, arg2):
            if arg1 is not None:
                return [opt, str(arg1)]
            elif arg2 is not None:
                return [opt, str(arg2)]
            return []

        cherrypy.response.stream = True
        cherrypy.response.headers['Content-Type'] = 'application/octet-stream'

        args = ['magewell2ts', '-m']
        args += coalesce('-i', input, arguments.input)
        args += coalesce('-b', board, arguments.board)
        args += coalesce('-v', verbose, arguments.verbose)
        args += coalesce('-c', codec, arguments.codec)
        args += coalesce('-d', device, arguments.device)
        if noAudio or arguments.noAudio:
            args += ['-n']
        args += coalesce('-a', lookAhead, arguments.lookAhead)
        args += coalesce('-q', quality, arguments.quality)
        args += coalesce('-g', gopSize, arguments.gopSize)
        args += coalesce('-p', preset, arguments.preset)
        print(f"args = {args}")

        def streamit():
            process = subprocess.Popen(
                args,
                stdout=subprocess.PIPE,
            )

            try:
                while True:
                    data = process.stdout.read(16384)
                    if not data:
                        print(f'## end of file detected', file=sys.stderr)
                        break
                    yield data
            except GeneratorExit:
                print(f'## generator exited', file=sys.stderr)
            except BrokenPipeError:
                print(f'## broken pipe error', file=sys.stderr)
            except Exception as e:
                print(f'## an error occurred: {e}', file=sys.stderr)
            print(f'## cleaning up', file=sys.stderr)
            process.kill()
            process.wait()
            print(f'## done', file=sys.stderr)

        return streamit()


parser = argparse.ArgumentParser(description="Magewell2TS web wrapper.")
parser.add_argument("-v", "--verbose", type=int, help="Verbosity level",
                    default=None)
parser.add_argument("-P", "--port", type=int, help="m2tsweb port nuymber",
                    default=6502)
parser.add_argument("-i", "--input", type=int, help="Default input",
                    default=1)
parser.add_argument("-b", "--board", type=int, help="Default board",
                    default=None)
parser.add_argument("-c", "--codec", type=str, help="Default codec",
                    default="hevc_qsv")
parser.add_argument("-d", "--device", type=str, help="Default render device",
                    default=None)
parser.add_argument("-n", "--noAudio", action="store_true",
                    help="Default no audio", default=None)
parser.add_argument("-a", "--lookAhead", type=int, help="Default look ahead",
                    default=None)
parser.add_argument("-q", "--quality", type=int, help="Default quality",
                    default=None)
parser.add_argument("-g", "--gopSize", type=float, help="Default GOP size",
                    default=None)
parser.add_argument("-p", "--preset", type=str, help="Default preset",
                    default=None)
arguments = parser.parse_args()


config = { 'global' :
           { 'server.socket_host' : '0.0.0.0',
             'server.socket_port' : arguments.port,
             'tools.encode.on' : True,
             'tools.encode.encoding':'utf8',
             'tools.encode.text_only' : False,
             'tools.decode.on' : True,
             'tools.trailing_slash.on' : True,
             'log.screen' : True
             },
        }


cherrypy.quickstart(RootPage(), config=config)
